Added imageOverrideLogo to HomeHero, tests
FutureNorthants/northants-design-system pull request #106
Opened 2022-01-27 16:22 UTC by DamienBurkeWN

### Testing

1. `npm test HomeHero`
2. Take a look at the HomeHero structure, there is a new story showing the overridden logo set to a simple placeholder image. Image is intended to be 520x150 pixels, and will be enforced as such in the CMS.
3. Verify that any London Bridge theme will display normal black/white logo, not the overridden logo (so, e.g., a temporary logo for a particular month won't override the memorial theme logo).

2022-01-27 16:23 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.stories.tsx
> -import React from "react";
Mostly Prettier reformatting and moving data out into storydata file

2022-01-27 16:24 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.stories.tsx
> +export const HomeHeroExampleOverriddenLogo = Template.bind({});
New story to show off the new control

2022-01-27 16:24 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.styles.js
> +export const LogoOverride = styled.div`
New bit

2022-01-27 16:25 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.test.tsx
> +  // run before each it() function, as otherwise things are cleaned up and subsequent it() calls go wrong
This comment belies 2 hours of angst

2022-01-27 16:25 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.tsx
> -import React, {useEffect, useRef, useState} from "react";
Some Prettier reformatting

2022-01-27 16:26 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.tsx
> +                  {imageOverrideLogo && !usingMemorialTheme && (
Only use the logo override if not in a memorial theme

2022-01-28 10:06 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.test.tsx
> +      console.log(typeof rendered);
Console log left in here

2022-01-28 10:24 UTC, chrisrhymes requested changes
Needs a bit of styling for smaller screen sizes

2022-01-28 10:24 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.styles.js
> +  img {
This needs some mobile/responsive styles as it stays 520px wide on mobile and goes out outside the container.

2022-01-28 10:24 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.types.ts
> +  imageOverrideLogo?: string;
Do we want the imageOverrideAltText as well that's specific to the overridden image?

2022-01-28 10:24 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.test.tsx
> +    rendered.getByText('To be on top');
Seems strange not having an expect() but I guess getBy throws an exception if it's not found so should be ok.

2022-01-28 10:24 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.storydata.ts
> +/**
Nice work, makes the other files much cleaner.

2022-01-28 12:46 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.types.ts
> +  imageOverrideLogo?: string;
Good call

2022-01-28 12:47 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.test.tsx
> +    rendered.getByText('To be on top');
Aye, a fail's a fail 😄

2022-01-28 15:54 UTC, chrisrhymes approved these changes

2022-01-31 10:45 UTC, merged