Make PromoBanner image clickable, add test
FutureNorthants/northants-design-system pull request #137
Opened 2022-02-23 17:06 UTC by DamienBurkeWN

### Testing
- Check out library/structure/promotional banner - verify image is now clickable and goes to same URL as call to action link
- `yarn test PromoBanner`

🪄 Reserving right to add protective div if it blows up on the frontend.

2022-02-23 17:07 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.stories.tsx
> +  argTypes: {
Mostly prettier but also adding the categories for controls

2022-02-23 17:08 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.storydata.tsx
> +export const PromoBannerContentText = "We’re looking for people to do this amazing thing in an amazing manner, during an amazing time of amazingness.";
Moved into a string so it can be picked up and referenced in the test

2022-02-23 17:08 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.styles.js
> +export const Image = styled.a`
The actual change 😆

2022-02-23 17:09 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.tsx
> -import React from "react";
Mostly prettier

2022-02-23 17:09 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.tsx
> +      {(src) => <Styles.Image img={src} href={ctaUrl} title={ctaText} />}
Adding href and title now it's an anchor not a div

2022-02-24 09:39 UTC, chrisrhymes requested changes
Just a couple of comments about the Image. The rest looks great.

2022-02-24 09:39 UTC, chrisrhymes commented on src/library/structure/PromoBanner/PromoBanner.tsx
> +      {(src) => <Styles.Image img={src} href={ctaUrl} title={ctaText} />}
Just thinking might be worth changing Image to ImageLink just so in future it's clearer it's not just an image?

2022-02-24 09:39 UTC, chrisrhymes commented on src/library/structure/PromoBanner/PromoBanner.tsx
> +      {(src) => <Styles.Image img={src} href={ctaUrl} title={ctaText} />}
Do we also need alt text for this background image somehow?

2022-02-24 09:51 UTC, DamienBurkeWN commented on src/library/structure/PromoBanner/PromoBanner.tsx
> +      {(src) => <Styles.Image img={src} href={ctaUrl} title={ctaText} />}
It's historically not had one hence why I've added the title attribute

2022-02-24 10:16 UTC, merged