Fix/warning text disclaimer link title
FutureNorthants/northants-design-system pull request #145
Opened 2022-03-01 14:40 UTC by chrisrhymes

Update the WarningTextDisclaimer link text and [remove the title](https://www.a11yproject.com/posts/creating-valid-and-accessible-links/#what-about-the-title-attribute%3F). 

Added test for the parent WarningText component and updated the files with prettier for consistency.

2022-03-01 14:41 UTC, chrisrhymes commented on src/library/slices/WarningTextDisclaimer/WarningTextDisclaimer.tsx
> +      <a href={'/your-council/about-website'}>Read more about the council changes</a>.
The actual change is removing the title and updating the link text

2022-03-04 14:21 UTC, DamienBurkeWN requested changes
Is the TODO still to be actioned or ...?

2022-03-04 14:21 UTC, DamienBurkeWN commented on src/library/slices/WarningText/WarningText.tsx
> +// @TODO this needs to fit within the content border
Is this comment still relevant?

2022-03-04 14:31 UTC, chrisrhymes commented on src/library/slices/WarningText/WarningText.tsx
> +// @TODO this needs to fit within the content border
I was going to ask you the same thing. Do you have any idea what it refers to?

2022-03-04 14:33 UTC, DamienBurkeWN commented on src/library/slices/WarningText/WarningText.tsx
> +// @TODO this needs to fit within the content border
Nope!

2022-03-04 14:43 UTC, DamienBurkeWN approved these changes
👍

2022-03-04 14:54 UTC, merged