Update PostCodeSearch placeholder
FutureNorthants/northants-design-system pull request #146
Opened 2022-03-02 15:53 UTC by chrisrhymes

Lots of changes for a placeholder text change... 

Managed to figure out how to mock axios (after many hours trawling stack overflow) so the tests shouldn't need access to the real api to run. This allows us to control the response. 

The tests wouldn't work with `e.target.postcode.value` in handleSubmit so I updated it to use `e.target.elements.postcode.value`. 

There was also a bug where it activated the loading state when the postcode was empty so it never displayed the error message.

2022-03-02 15:54 UTC, chrisrhymes commented on src/library/components/FormWithLine/FormWithLine.tsx
> +        data-testid="FormWithLine"
Added data-testid as the fireEvent.click wouldn't work. This allowed me to use fireEvent.submit() in the test.

2022-03-02 15:56 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +    const enteredPostcode = e.target.elements.postcode.value;
Updated to use `elements` and created variable to reuse.

2022-03-02 15:58 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +                      placeholder="Search postcode"
The actual change, updating the placeholder to be unique when used on a page with a search bar.

2022-03-02 16:05 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +      setIsLoading(true);
The `setIsLoading(true)` was in the wrong place so you never saw the error message.

2022-03-04 15:05 UTC, DamienBurkeWN requested changes
As well as the individual comments to look at, there's a behaviour change introduced here. If you enter an unknown or outside-Northants postcode, your input used to be retained in the input so that you could - for instance - easily correct a typo. Now it is discarded entirely so you have to re-enter from scratch, and have reduced feedback on whether it was your fault.

2022-03-04 16:44 UTC, chrisrhymes commented on src/library/components/Input/Input.tsx
> -      <Styles.StyledInput type={type} placeholder={isErrored ? "Enter a postcode" : placeholder} name={name} isErrored={isErrored} />
Not sure why a generic component has a hardcoded string for an error state, so reverted to always use the provided placeholder. The rest is prettier

2022-03-04 16:46 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.styles.js
> +  display: ${(props) => (props.isLoading ? `none` : 'block')};
Added css to hide the form container when isLoading. This way it keeps the state rather than removing and adding the form after loading.

2022-03-04 16:47 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +              <Styles.FormContainer isLoading={isLoading}>
Hide form with CSS when isLoading instead of removing from the page.

2022-03-09 10:51 UTC, DamienBurkeWN approved these changes
Good stuff 👍

2022-03-10 09:11 UTC, merged