Services Links Boxed
FutureNorthants/northants-design-system pull request #169
Opened 2022-04-05 14:05 UTC by chrisrhymes

This has turned into a very large pull request... 

Includes:
- New reusable grid components (row and column) and documentation page added
- Service links boxed alternative for the homepage
- Set isBoxed to true in ServicesLinksList to display the boxed version
- HeadingWithIcon can now have a hover effect if required
- Homepage story added to show the isBoxed version

2022-04-25 14:47 UTC, chrisrhymes commented on src/library/structure/ServicesLinksBoxed/ServicesLinksBoxed.tsx
> +  let refs = React.useRef([]);
Using useRef to get the height for each of the QuickLinksContainer to prevent ServiceLinks from being covered when the menu appears

2022-04-29 14:08 UTC, chrisrhymes commented on src/library/components/HeadingWithIcon/HeadingWithIcon.stories.tsx
> +export const H1WithHover = Template.bind({});
New story to show the hover effect

2022-04-29 14:09 UTC, chrisrhymes commented on src/library/components/HeadingWithIcon/HeadingWithIcon.styles.js
> +  .service-icon-hover {
Mainly prettier in this file, except the addition of the .service-icon styles

2022-04-29 14:11 UTC, chrisrhymes commented on src/library/pages/Home/HomePage.stories.tsx
> +  servicesArray: ServiceLinksArray,
Reuse storydata for ServiceLinksArray

2022-04-29 14:12 UTC, chrisrhymes commented on src/library/pages/Home/HomePage.tsx
> +        <PageStructures.PromoBlock promos={promoBlocksArray.slice(0, numberOfPromos - 1)} />
Move PromoBlock to above ServiceLinksList as per latest design

2022-05-03 10:50 UTC, DamienBurkeWN requested changes
Works well, couple of documentation nitpicks commented on.
The bug with text overlaying icons is really obvious now on desktop but entirely absent in mobile view, is it worth dealing with in this PR?

2022-05-03 10:50 UTC, DamienBurkeWN commented on src/docs/3GridSystem.stories.mdx
> +You may also pass in `hasBorder` into the Column props to display the border. This should only be used for demonstration purposes in development and not in the production code.
Row props?

2022-05-03 10:50 UTC, DamienBurkeWN commented on src/library/components/Column/Column.test.tsx
> +  it('should the content', () => {
should what? :)

2022-05-03 10:50 UTC, DamienBurkeWN commented on src/library/pages/Home/HomePage.stories.tsx
> +  servicesArray: ServiceLinksArray,
👍

2022-05-03 10:50 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksBoxed/ServicesLinksBoxed.types.ts
> +  serviceLinksArray: Array<PageLinkProp>;
I guess this is historic but data type in the name, urgh...

2022-05-03 12:14 UTC, chrisrhymes commented on src/library/components/HeadingWithIconLink/HeadingWithIconLink.styles.js
> +  flex-shrink: 0;
Fix the issue with heading crowding/overlapping the icon by preventing the icon shrinking.

2022-05-03 15:09 UTC, merged