Add aria-label to sort buttons in ServicesLinksList
FutureNorthants/northants-design-system pull request #176
Opened 2022-04-20 14:40 UTC by chrisrhymes

Add aria-label to sort buttons to help prevent accessibility issue STAS-F03: Ambiguous Button Labelling on the ServicesLinksList on the homepage.

2022-04-20 14:40 UTC, panosp17 commented
Task linked: [CU-2v8vp6d P1 - Accessibility issue STAS-F03: Ambiguous Button Labelling](https://app.clickup.com/t/2v8vp6d)

2022-05-03 10:53 UTC, DamienBurkeWN requested changes

2022-05-03 10:53 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksList/ServicesLinksList.tsx
> +                    aria-label="Order services by alpabetical order"
Suggest "Order services alphabetically"

2022-05-03 10:53 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksList/ServicesLinksList.tsx
>                      name="alphabatical services"
"alphabetical"

2022-05-03 10:53 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksList/ServicesLinksList.tsx
> +                    aria-label="Order services by alphabetical order"
Same suggestion as above

2022-05-03 12:37 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksList/ServicesLinksList.tsx
> +                    aria-label="Order services alpabetically"
missing h

2022-05-03 13:26 UTC, DamienBurkeWN approved these changes
👍

2022-05-03 13:27 UTC, merged