Clicking link in alert banner dismisses banner
FutureNorthants/northants-design-system pull request #191
Opened 2022-05-16 16:24 UTC by DamienBurkeWN

## Testing
* In Storybook you can play with the AlertBanner structure to verify that clicking a link within a banner also dismisses it
* Also fixed the bug whereby a dismissed site alert still flashes up briefly on initial page load in production build; `yalc publish` this branch and on the frontend `yalc add northants-design-system && yarn install && yarn bs`, set a sitewide alert in the CMS, load homepage in frontend, dismiss it, reload page, verify no banner flash.

2022-05-16 16:25 UTC, DamienBurkeWN commented on src/library/structure/AlertBanner/AlertBanner.stories.tsx
> +      <Button url={null} onClick={resetAlert}>Click to reset</Button>
Just for our convenience...

2022-05-17 10:30 UTC, chrisrhymes requested changes
Something is not quite right. If you go on the positive alert example and then dismiss it, then "Click to reset" it is no longer blue, but has a red background? Not sure if it always did that.

2022-05-17 10:30 UTC, chrisrhymes commented on src/library/structure/AlertBanner/AlertBanner.stories.tsx
>    </p>
Is it worth setting the href="#" so it doesn't redirect to the homepage of storybook?

2022-05-17 10:30 UTC, chrisrhymes commented on src/library/structure/AlertBanner/AlertBanner.stories.tsx
> +      <Button url={null} onClick={resetAlert}>Click to reset</Button>
Nice!

2022-05-17 16:11 UTC, DamienBurkeWN commented on src/library/structure/AlertBanner/AlertBanner.stories.tsx
> +    window.location.replace(window.location.href.split('&')[0]);
For some reason storybook had rewritten the URL to include empty args, so the straight reload() call ended up with an undefined type for the alert type arg. This strips out any args and I've used replace() so your browser history isn't cluttered with another entry too.

2022-05-18 10:46 UTC, chrisrhymes approved these changes
👍

2022-05-18 13:45 UTC, merged