Add card component and cards slice
FutureNorthants/northants-design-system pull request #199
Opened 2022-05-24 15:24 UTC by chrisrhymes

Draft PR to generate Netlify preview

- Create a Card component
- Create a Cards slice that allows for multiple cards to be presented in a grid

2022-05-26 09:56 UTC, MeganCrowthers commented
Task linked: [CU-2849g6m 3 column text slice (post-its)](https://app.clickup.com/t/2849g6m)

2022-05-27 10:56 UTC, DamienBurkeWN requested changes
Needs a bit of tweaking to better handle being used as triple image slice - currently, content is mandatory, and if you don't set anything except the image, there's a blank white bit at the bottom of the card.

2022-05-27 10:56 UTC, DamienBurkeWN commented on src/library/components/Card/Card.types.ts
> +  imageAltText?: string | null;
Why the | null, isn't the question mark enough?

2022-05-27 10:56 UTC, DamienBurkeWN commented on src/library/components/Card/Card.types.ts
> +  /** Optional large image */
Formatting different to all the other comments

2022-05-27 10:56 UTC, DamienBurkeWN commented on src/library/components/Card/Card.types.ts
> +  content: string;
Shouldn't this be optional, so that cards can be used as a triple image slice - no content, no heading, no footer, just images set

2022-05-27 14:00 UTC, chrisrhymes commented on src/library/components/Card/Card.types.ts
> +  imageAltText?: string | null;
The frontend was complaining that the types were incompatible with the GraphQL types

2022-06-07 08:09 UTC, merged