Allow Image component to have text wrapped up against it
FutureNorthants/northants-design-system pull request #202
Opened 2022-05-25 14:59 UTC by DamienBurkeWN

### Testing
* Look at Image stories 
* Probably best tested with real content in frontend, PRs to follow

2022-05-25 15:06 UTC, DamienBurkeWN commented on src/library/slices/Image/Image.styles.js
> +  float: ${(props) => (props.wrapText === true ? 'left' : 'none')};
So basically just drop the image size down and float it to the left if wrapText is used, but only on screens bigger than mobile

2022-05-25 15:06 UTC, DamienBurkeWN commented on src/themes/theme_generator.jsx
> +                    max-width: 55rem;
While I was there, the slight increase in available space discussed on Slack

2022-05-26 12:18 UTC, DamienBurkeWN commented on .storybook/preview.js
> -import { addDecorator } from '@storybook/react';
Wasn't used

2022-05-26 12:19 UTC, DamienBurkeWN commented on .storybook/preview.js
> -import { createGlobalStyle } from 'styled-components';
No longer necessary

2022-05-26 12:20 UTC, DamienBurkeWN commented on src/library/structure/PageMain/PageMain.styles.js
> -    ul, ol {
Removed all this stuff putting back in margins and a bullet disc at a hard-coded position!

2022-05-26 12:20 UTC, DamienBurkeWN commented on src/themes/GlobalStyleReset.jsx
> +import { createGlobalStyle } from 'styled-components';
This is basically reset.css

2022-05-26 12:21 UTC, DamienBurkeWN commented on src/themes/GlobalStyleReset.jsx
> +    list-style: decimal inside;
...with sensible list defaults

2022-05-26 13:47 UTC, chrisrhymes requested changes
Good way of modifying an existing component to work with the content.

My question is does the add value to the page if it's smaller? Wider discussion point I guess.

> Avoid unnecessary decoration. Only use images if there’s a real user need.
https://design-system.service.gov.uk/styles/images/

- I think the margin-left needs to be reduced compared to previous styling
- The [Contents component](https://northants-design-system.netlify.app/?path=/story/page-examples-service-page-example--service-page-with-contents) styling has now changed after the defaults have been changed. 
- The footer links appear out of line with the icons below
- The ServiceLinksList now have two bullets

2022-05-26 13:47 UTC, chrisrhymes commented on src/themes/GlobalStyleReset.jsx
> +    list-style: decimal inside;
The 2rem margin-left feels too much to me, 1 or 1.25 would be better. It's now 32px rather than the previous 20px.

2022-05-26 14:55 UTC, DamienBurkeWN commented on src/library/structure/Footer/Footer.styles.js
> +  margin-left: 0;
Fix for alignment shift

2022-05-26 14:56 UTC, DamienBurkeWN commented on src/library/structure/ServicesLinksList/ServicesLinksList.styles.js
> +  list-style-type: none;
Fix for double discs

2022-05-26 14:57 UTC, DamienBurkeWN commented
Does it add value... well that's for the marketing boys. I don't think it will be used on purely informational pages, more for the flashier marketing driven campaign style pages.

2022-05-26 15:03 UTC, DamienBurkeWN commented on src/library/structure/ContentsNavigation/ContentsNavigation.stories.tsx
> -import { ContentsArray } from '../Contents/Contents.storydata';
Bonus bugfix

2022-05-26 16:01 UTC, chrisrhymes requested changes
If the list item contains long text then subsequent lines aren't indented to where the first line text starts. This doesn't look right to me. 
<img width="580" alt="Screenshot 2022-05-26 at 16 59 11" src="https://user-images.githubusercontent.com/4160546/170526976-2a6e50ff-c147-4b5c-89bb-da5fba0cc108.png">

2022-05-27 13:33 UTC, chrisrhymes approved these changes
Gotta love CSS!
![image](https://user-images.githubusercontent.com/4160546/170709640-7b9328fb-9f9b-4e63-9624-f83250e1dd88.png)

2022-06-01 10:30 UTC, merged