Display service icons in Iconography docs
FutureNorthants/northants-design-system pull request #246
Opened 2022-07-20 08:41 UTC by chrisrhymes

- Remove the icon stories and display them in the [iconography docs page](https://deploy-preview-246--northants-design-system.netlify.app/?path=/docs/documentation-iconography--all-service-icons)
- Refactor the service icons so that they have consistent directory naming and the Icon and IconHover are in the same directory (for example PlanningIcon/Icon -> Planning/Icon)
- Update imports in ServiceIcons.ts

2022-07-20 14:32 UTC, DamienBurkeWN commented
Brilliant! Make it so!

2022-08-08 07:02 UTC, MeganCrowthers commented
Task linked: [CU-2pe5pbf Icons documentation refactoring](https://app.clickup.com/t/2pe5pbf)

2022-08-15 12:27 UTC, DamienBurkeWN requested changes

2022-08-15 12:27 UTC, DamienBurkeWN commented on src/docs/4Iconography.stories.mdx
> +There are three main types of icons used in the design system.
Not sure why but all this text does not display for me unless I toggle to the docs panel. All the other docs pages display correctly in both canvas and docs panels?

2022-08-15 12:43 UTC, chrisrhymes commented on src/docs/4Iconography.stories.mdx
> +There are three main types of icons used in the design system.
It seems this is the way storybook is designed to work. 

If you include `<Story>` in your mdx file then the text around stories will only appear in the docs tab. 

> To get a "documentation-only story" in your UI, define a <Meta> as you usually would, but don't define any stories. It will show up in your UI as a documentation node
- https://storybook.js.org/docs/react/api/mdx#documentation-only-mdx

2022-08-15 13:21 UTC, DamienBurkeWN approved these changes
👍

2022-08-15 14:18 UTC, merged