Visually hidden heading
FutureNorthants/northants-design-system pull request #312
Opened 2022-12-15 13:05 UTC by chrisrhymes

Sitemorse has flagged that the homepage doesn't have a H1. It is in the html, but had the style `visibility: hidden` so was not accessible to screen readers. The styles have been updated to use the VisuallyHidden helper. 

Also adjusted the svg top margin to compensate for the change in styles. 

## Testing
- Revert HiddenH1 styles to visually hidden and run tests. See that 'it should render the heading one' test fails
- Undo change and test should now pass
- Test HomeHero svg still aligns correctly with the updated top margin

2022-12-15 13:05 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.styles.js
> +  ${(props) => VisuallyHidden};
The main change is here, replacing `visibility: hidden`

2022-12-15 13:06 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.styles.js
> +    margin-top: -20px;
Adjusted negative margin now that the heading one is 1px high instead of previous height.

2022-12-15 13:07 UTC, chrisrhymes commented on src/library/structure/HomeHero/HomeHero.tsx
> +                  <Styles.HiddenH1>{`${themeContext.full_name} Council`}</Styles.HiddenH1>
Additional fix, use template literal to remove the unnecessary html comment from inside the rendered h1 tag.

2022-12-15 13:44 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.tsx
> +                  <Styles.HiddenH1>{`${themeContext.full_name} Council`}</Styles.HiddenH1>
Whaaaaat

2022-12-15 13:50 UTC, DamienBurkeWN requested changes

2022-12-15 13:50 UTC, DamienBurkeWN commented on src/library/structure/HomeHero/HomeHero.styles.js
> +    margin-top: -20px;
Visual difference. Needs to be -17px

2022-12-16 09:33 UTC, MeganCrowthers commented
Task linked: [CU-862hxewpm Homepage h1 tag has visibility hidden](https://app.clickup.com/t/862hxewpm)

2022-12-16 11:56 UTC, DamienBurkeWN approved these changes
👍

2022-12-16 13:17 UTC, merged