Add dropdown for postcode radius search on directory service list
FutureNorthants/northants-design-system pull request #425
Opened 2024-03-05 10:19 UTC by chrisrhymes

- Initial layout for proximity dropdown

2024-03-13 12:48 UTC, DamienBurkeWN requested changes
Dropdown isn't defaulting to 2 miles, it's empty.
Dropdown is appearing grey - I'd assumed disabled - but it isn't.
Should dropdown be useable if postcode isn't entered?

2024-03-13 12:48 UTC, DamienBurkeWN commented on src/library/directory/DirectoryServiceList/DirectoryServiceList.tsx
> +                        { title: '20+ miles', value: '50' },
Description and limit don't match - should this be a limit of 20 or a limit of 50?

2024-03-13 13:16 UTC, chrisrhymes commented on src/library/directory/DirectoryServiceList/DirectoryServiceList.tsx
> +                        { title: '20+ miles', value: '50' },
The radius has to be an integer, so setting to 50 to include most of West Northamptonshire. 

The new meilisearch will use the [_geoRadius](https://www.meilisearch.com/docs/learn/fine_tuning_results/geosearch#_georadius) method so needs a distance value (the backend will turn the miles into metres.

2024-03-13 13:43 UTC, DamienBurkeWN commented on src/library/directory/DirectoryServiceList/DirectoryServiceList.tsx
> +                        { title: '20+ miles', value: '50' },
So shouldn't the title be '50 miles'? As 51 is '20+' but wouldn't be included.

2024-04-03 09:33 UTC, chrisrhymes commented
More research and feedback needed for this feature so converting to a draft pull request.

2025-06-23 08:46 UTC, closed without merging