Add error message when too many addresses returned
FutureNorthants/northants-design-system pull request #461
Opened 2024-04-18 15:41 UTC by chrisrhymes

Resolves #460 

## Testing
- Checkout this branch and run `npm run dev`
- Visit the Slices -> Bin Finder page
- Enter `NN1 5PH` for the postcode and press find, then enter `1` as the address and press find.
- The error message should display.

2024-04-19 07:25 UTC, chrisrhymes commented on src/library/slices/BinFinder/BinFinder.tsx
> +    const formattedPostcode = data.postcode.replace(/ /g, '').substring(0, 10);
Creating variables to make the get path easier to read.

2024-04-19 07:26 UTC, chrisrhymes commented on src/library/slices/BinFinder/BinFinder.tsx
> +          if (showFirstLine) {
If the first line is already shown, then display the error message. This prevents their being an error the first time the first line of address input is shown.

2024-04-22 08:26 UTC, DamienBurkeWN requested changes
Works but I think it could do with a couple of variations on the error message depending upon whether there are any results or too many; also, I think this is a bit fundamentally broken regardless. E.g. search for NN1 5PH and 'Room 12' - nope. '12' - nope. '27' - bingo, includes the Room 12 we wanted? I would expect it show all the addresses with Room 12 if I search for Room 12?

2024-04-22 08:26 UTC, DamienBurkeWN commented on src/library/slices/BinFinder/BinFinder.tsx
> +                'This address could not be found based on the information given. Please try entering further information.',
Not strictly accurate (as it could be too many results not zero). How about "Sorry, there are still too many results. Please try being more specific e.g. door number and street name together" for when there are results?

2024-04-23 11:53 UTC, chrisrhymes commented on src/library/slices/BinFinder/BinFinder.tsx
> +                'This address could not be found based on the information given. Please try entering further information.',
Thanks, I have asked for feedback and they want to keep the text as previously agreed.

2024-04-23 12:00 UTC, chrisrhymes commented
@DamienBurkeWN  I have created #468 in the issues tab to capture your feedback about the room 12 issue with the search. Updates to the API are in development, which will then require further frontend development to integrate the changes.

2024-04-23 12:12 UTC, DamienBurkeWN approved these changes

2024-04-23 12:20 UTC, merged