Autocomplete component
FutureNorthants/northants-design-system pull request #71
Opened 2021-11-01 12:21 UTC by DamienBurkeWN

Relates to https://github.com/FutureNorthants/northants-design-system/issues/69

Likely to need further work.

2021-11-01 12:32 UTC, DamienBurkeWN commented on util/create-component.js
> -const componentDirectory = `./src/${componentName}`;
Changed these as I found the readme instructions for creating a new component ended up with the created files in the wrong place.

2021-11-02 12:19 UTC, apricot13 requested changes

2021-11-02 12:19 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.types.ts
> +    name: string;
in storybook the block comment above these becomes the description for the description field in the docs section:

![image](https://user-images.githubusercontent.com/649148/139842270-33f4dd3b-65e5-48e0-80a6-6d6e62118be2.png)

2021-11-02 12:19 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +export const AutocompleteSuggestionItem = styled.li`
for the styling we try to follow the gov uk styles as much as possible. 
For this I would use the following. 
![image](https://user-images.githubusercontent.com/649148/139843374-f0d91686-738b-4756-90d4-a772182a3392.png)

2021-11-02 12:19 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +    border: 1px solid darkgray;
all colours should be sourced from the props, so the border here will be the same as the colour used by the input styles. Same with any radius, font size or spacingSizes we set - each theme has it slightly different.

2021-11-02 12:19 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +    border-radius: 5px; !important
you should never need to use `!important` - you also have a syntax error here though it will go away with the govuk restyling anyway!

2021-11-02 12:22 UTC, apricot13 commented on util/create-component.js
> -const componentDirectory = `./src/${componentName}`;
yeh it puts them outside the library by default so you dont have to go digging too far!

2021-11-02 12:25 UTC, apricot13 requested changes

2021-11-02 12:25 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.tsx
> +import { action } from '@storybook/addon-actions';
this very likely will cause all sorts of issues when this is exported out and used in the frontend - you can test it locally in the frontend using yalc (instructions are in the readme). instead of using the frontend I sometimes use this as a test environment for single components: https://github.com/apricot13/FN-IE11-react-test-env

2021-11-02 15:54 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.types.ts
> +    name: string;
Didn't work for me, the description fields are being picked up from the ArgTypes export in the stories file.

2021-11-02 15:55 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.tsx
> +import { action } from '@storybook/addon-actions';
Good spot, should have thought that one through - action handling now moved to the stories file where it should have been.

2021-11-02 16:27 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +export const AutocompleteSuggestionItem = styled.li`
Try now?

2021-11-03 08:54 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +export const AutocompleteSuggestionItem = styled.li`
![image](https://user-images.githubusercontent.com/649148/140031850-9797db28-6b36-4e0c-bdc5-a13ce2447ed8.png)
ooh much better! Theres an issue with the borders though they're all different widths, the auto complete box is 1px wider on the right hand side too it looks like.

2021-11-03 08:55 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.types.ts
> +    name: string;
ah ok - would you mind addin gthem to the types.ts too - since every other component is in there. 
we use the .types.ts file in the npm package in the frontend too - It may help with code completion in there too (but I dont actually know that for sure!)

2021-11-03 10:49 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.types.ts
> +    name: string;
Done - it appears Storybook doesn't update the displayed docs unless stopped and restarted!

2021-11-03 10:50 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +export const AutocompleteSuggestionItem = styled.li`
Fixed the width, don't see a difference in borders?

2021-11-03 14:25 UTC, DamienBurkeWN commented on src/index.ts
> +export {
Just reformatted to get rid of the enormous long line

2021-11-03 14:26 UTC, DamienBurkeWN commented on src/library/structure/NewsArticleFeaturedBlock/NewsArticleFeaturedBlock.tsx
> +import Heading from "../../components/Heading/Heading";
Referencing the component directly rather than via the index.ts, which creates a circular reference

2021-11-11 19:01 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.tsx
> +                isOpen: isOpen && filteredsuggestions.length > 0,
A tweak so the squared off lower border doesn't become near-permanent once the list has displayed once

2021-11-18 12:52 UTC, AnthonyTaylor approved these changes

2021-11-23 17:23 UTC, merged