Styles for autocomplete
FutureNorthants/northants-design-system pull request #72
Opened 2021-11-03 19:04 UTC by apricot13

Small PR for the auto complete - there was an issue with the margin-top making it look like a 3px border and the thicker bottom border was from the list items inside bottom border. also I brought it up a bit so needed to do some radius swapping though thinking now you could just bring it up a few px more and that wouldn't be an issue

2021-11-04 13:55 UTC, DamienBurkeWN requested changes

2021-11-04 13:55 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.styles.js
> +    /* background: ${props => props.isOpen ? "red" : "2px"} */
Guessing you didn't mean to leave this bit in?

2021-11-04 13:55 UTC, DamienBurkeWN commented on src/library/components/Autocomplete/Autocomplete.tsx
> +                isOpen: isOpen
...and that isOpen isn't needed here as a result too.

2021-11-04 15:25 UTC, apricot13 commented on src/library/components/Autocomplete/Autocomplete.tsx
> +                isOpen: isOpen
isOpen is still needed for the borders 👍

2021-11-05 08:51 UTC, DamienBurkeWN approved these changes

2021-11-05 08:51 UTC, merged