Feature/council tax new api
FutureNorthants/northants-design-system pull request #77
Opened 2021-11-26 16:02 UTC by apricot13

### This PR has two commits (so far)

1. Updating the new (currently not used on the website) council tax page elements.
2. Updating the [signposting page tool](https://www.westnorthants.gov.uk/bins-recycling-and-street-cleaning/garden-waste) to use the new API endpoint as well

### Notes from Mike C:
* Please note that the **ctaxband** and **ctaxamount** are still showing null 
* There is also an issue with **Parishes being wrong** which is being worked on
* The final piece of work will be to place the above endpoint under a more friendly .digital domain (or similar) but feel free to use the above in the mean time. **(HN: I have updated the code to use environment vars so we will just need to do a redeploy when urls change)**

### Notes from Me:
* Theres no API key requirement yet so that code is commented out
* There is no new API for the [A-Z parish page](https://northants-design-system.netlify.app/?path=/story/page-examples-council-tax-prototypes-by-parish--version-d) though its might well be redundant with the other work.
* The signposting section update: there is no longer a sovereignCode associated with the new API data so there are no longer (in this PR) any signPostLinks being shown - I'm not 100% sure if we're using them anywhere or not. I'll look further into this.

### Next Steps:
* Integrate this with the frontend as a new slice. Will need to add in the new environmental variables as well for the API.
* Wait for API to be update and put onto its own URL then redeploy with the new url in environmental variables
* Wait for API ctaxamout, ctaxband and parish to reflect most up to date information.

cc @AnthonyTaylor, @DamienBurkeWN, @markpdeeson, @KevinWhite

2022-02-09 17:18 UTC, apricot13 commented
One more update - the parish a-z page now fetches data from the API

2022-06-01 14:05 UTC, chrisrhymes commented on .storybook/main.js
> +  env: (config) => ({
Add these vars for when the design system is deployed to netlify. 
https://storybook.js.org/docs/react/configure/environment-variables#using-storybook-configuration

2022-06-20 15:46 UTC, chrisrhymes commented on src/library/components/PostCodeAddressDropdown/PostCodeAddressDropdown.tsx
> +                    {Object.keys(currentAddress.extra.bands).map((band) => (
Display a table of council tax bands for the address as we don't yet know the council tax band

2022-06-21 15:03 UTC, DamienBurkeWN requested changes
Pretty solid work but I think the API responses need some work, see individual comments.

2022-06-21 15:03 UTC, DamienBurkeWN commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +export interface AddressArrayProps {
Naming - no need for Array in name, suggest AddressesProps?

2022-06-22 07:53 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +        if (responseData.numOfUnitary > 0) {
The `response.data` is remapped into the `responseData` object above, so this is where numOfUnitary is set.

2022-06-22 07:57 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +  numOfSovereign: number;
This is the type for the remapped `responseData` object

2022-06-22 08:34 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +  single_line_address: string;
The age old question, snake_case or camelCase? As long as it isn't SCREAMING_SNAKE_CASE

2022-06-22 09:35 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
> +                    maxLength={10}
Added HTML maxlength attribute of 10 characters

2022-06-22 09:42 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +  ctaxband: string;
Not in api response so removed

2022-06-22 09:42 UTC, chrisrhymes commented on src/library/slices/CouncilTaxAlphabeticalDirectory/CouncilTaxAlphabeticalDirectory.tsx
> +      if (!r[group]) r[group] = { group, children: [{ title: e.banding_parish, values: e.bands }] };
Refactored

2022-06-22 09:43 UTC, chrisrhymes commented on src/library/slices/CouncilTaxAlphabeticalDirectory/CouncilTaxAlphabeticalDirectory.types.ts
> +export interface Parish {
Renamed as per suggestion

2022-06-22 09:45 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +export interface AddressArrayProps {
Renamed to `AddressOption` as it is used as the options for the DropDownSelect

2022-06-22 09:49 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +  numOfUnitary: number;
Refactored code and removed this

2022-06-23 15:52 UTC, MeganCrowthers commented
Task linked: [CU-2v8vp7r Directories - Council Tax](https://app.clickup.com/t/2v8vp7r)

2022-06-27 09:46 UTC, DamienBurkeWN commented on src/library/contexts/PostCodeAddressProvider/PostCodeAddressProvider.types.ts
> +export interface AddressProps {
We should probably be using a single helper for the API access then, keeps that DRY. I'm already in two minds about API use being embedded with the design system components; yes it makes testing easier but it feels like we're tying business logic into a presentation layer. In the case of the council tax stuff, if the backend were doing the API calls, at least it could cache the results for all. With it embedded in the design system, we can only cache for an individual visitor. Worthy of a discussion with more devs involved.

2022-06-29 10:43 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.tsx
>            handleError(true);
Mike has now updated the API responses to be more consistent and provide the relevant response codes.

2022-06-29 12:11 UTC, chrisrhymes commented on src/library/components/PostCodeSearch/PostCodeSearch.types.ts
> +  single_line_address: string;
API and types are now all snake case

2022-06-29 12:12 UTC, chrisrhymes commented on src/library/contexts/PostCodeAddressProvider/PostCodeAddressProvider.types.ts
> +export interface AddressProps {
The API response props have been extracted to the api-helper.ts file to remove the duplication.

2022-06-29 15:48 UTC, DamienBurkeWN requested changes
Some nitpicky language/comment stuff to sort.

Additionally:

If your postcode + filter results in only one address, you are told there are '1 addresses' and the dropdown still needs to be manually selected. Be nice - not essential - if the language was correct and the address auto selected in that instance?

2022-06-29 15:48 UTC, DamienBurkeWN commented on src/library/pages/CouncilTaxPageExample/CouncilTaxPageExample.stories.tsx
> +// export const VersionC = Template.bind({});
Can kill this off

2022-06-29 15:48 UTC, DamienBurkeWN commented on src/library/pages/CouncilTaxParishPageExample/CouncilTaxParishPageExample.stories.tsx
> +//version d
Comment to kill?

2022-07-01 09:51 UTC, chrisrhymes commented on src/library/components/PostCodeAddressSearch/PostCodeAddressSearch.tsx
> +                  {Number(results.total_records) > 1 ? `addresses` : `address`} found.
Plural for multiple results matched

2022-07-01 10:46 UTC, chrisrhymes commented on src/library/components/PostCodeAddressDropdown/PostCodeAddressDropdown.tsx
> +    if (addresses.length > 1) {
😢 This doesn't work as expected. It selects the address but doesn't trigger the on change event to set the address. I will look into this next week.

2022-07-04 07:46 UTC, chrisrhymes commented on src/library/components/PostCodeAddressDropdown/PostCodeAddressDropdown.tsx
> +    if (addresses.length === 2 && currentAddress?.value !== addresses[1].value) {
This now sets the currentAddress automatically if there is one option (one and the placeholder). It checks if the current address is different before setting, otherwise it causes a recursive loop where it re-renders the component after the address has changed.

2022-07-04 07:47 UTC, chrisrhymes commented on src/library/components/PostCodeAddressDropdown/PostCodeAddressDropdown.tsx
> +            selected={currentAddress ? currentAddress.value : hasResults ? 'choose-address' : 'no-results'}
The currentAddress.value updates the select to display the currentAddress as the selected option when it is automatically updated when only one option.

2022-07-04 09:53 UTC, DamienBurkeWN approved these changes
👍 🥳 🍾

2022-07-05 10:19 UTC, merged