Feature/video component
FutureNorthants/northants-design-system pull request #85
Opened 2021-12-16 10:50 UTC by chrisrhymes

Video component that allows a YouTube video to be embedded with the YouTube id. The container is set to 16 by 9 ratio, so it is responsive to the device.

2021-12-16 11:17 UTC, DamienBurkeWN commented on src/library/components/Video/Video.styles.js
> +  padding-top: 56.25%;
What's the magic that makes this figure work? I thought 50 would have been right but it clearly isn't.

2021-12-16 11:17 UTC, DamienBurkeWN commented on src/library/components/Video/Video.styles.js
> +  }
Shouldn't we be turning off any border here?

2021-12-16 11:18 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> +
Tidy - no need for this blank line

2021-12-16 11:19 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> +const Video: React.FC<VideoProps> = ({ youtube_id }) => (
Could do with a comment block here describing the component (shows up in Storybook), and I've been using .FunctionComponent rather than .FC for clarity/readability, I think it helps when new to React that you know explicitly what it's doing

2021-12-16 11:20 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> +      frameborder="0"
This isn't a valid attribute any more is it? Should be handled in the css?

2021-12-16 11:20 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> +      allowfullscreen
Another invalid attribute - should be 'fullscreen' in the allow list above

2021-12-16 11:26 UTC, DamienBurkeWN requested changes
Nice and simple but 3 more things over and above the comments. 

First off I presume including package-lock.json was a mistake, there's no package changes.

Second, I assume there's a slice to follow this which will either make use of this component or a link to the video if the user said no to cookies?

Third, could this component be more generic - e.g. support Vimeo or other video platforms, rather than being specifically Youtube? I'm thinking whilst the current two councils have youtube channels, microsite owners may want to use other or multiple platforms.

2021-12-16 11:27 UTC, DamienBurkeWN commented on src/library/components/Video/Video.styles.js
> +  padding-top: 56.25%;
Ah never mind, 16/9 - gotcha!

2021-12-16 15:57 UTC, chrisrhymes commented on src/library/components/Video/Video.tsx
> +const Video: React.FC<VideoProps> = ({ youtube_id }) => (
Didn't know about the comment, thanks. I've added the comment and used FunctionComponent.

2021-12-16 15:58 UTC, chrisrhymes commented on src/library/components/Video/Video.tsx
> +      frameborder="0"
I've applied the border style to the styles.

2021-12-16 15:58 UTC, chrisrhymes commented on src/library/components/Video/Video.tsx
> +      allowfullscreen
I have added 'fullscreen' to the allow.

2021-12-16 17:19 UTC, DamienBurkeWN approved these changes
Spot on. Just a couple of comment lines to kill and all done I think.

2021-12-16 17:19 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> + * @param param0
Just a whoops on the needless param and return in the docblock

2021-12-17 13:00 UTC, DamienBurkeWN approved these changes

2021-12-21 11:25 UTC, chrisrhymes commented
Refactored the video component to display a link when the cookies are not accepted and added tests.

2021-12-22 09:28 UTC, DamienBurkeWN commented on src/library/components/Video/Video.stories.tsx
> +import React from 'react';
As it's to be directly used as a slice rather than being a component in a slice, I think all this lot needs to be moved into src/library/slices

2021-12-22 10:01 UTC, DamienBurkeWN commented on src/library/components/Video/Video.tsx
> +import Button from '../Button/Button';
This import isn't used

2021-12-22 10:03 UTC, DamienBurkeWN requested changes
Looks good, as per comment needs moving from components to slices. Also still needs the package-lock.json file taking out.

2021-12-22 15:06 UTC, DamienBurkeWN requested changes
![image](https://user-images.githubusercontent.com/91884003/147113024-7a388624-4d53-4222-a8e3-614de2410dcf.png)

2021-12-22 16:30 UTC, DamienBurkeWN approved these changes
Nice

2022-01-04 10:14 UTC, merged